config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  resources :posts
  post 'post/modal', to:'posts#modal', as: :post_modal
  post 'post/modal/create', to:'posts#troll', as: :post_troll

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#results'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers:        {omniauth_callbacks: "omniauth_callbacks"}

  get 'guide', to: 'home#guide'
  get 'video', to: 'home#video'
  root 'home#index'

  get 'sign_up/modal', to: 'home#sign_up_modal', as: :sign_up_modal

  namespace :api do
    namespace :v1 do
      namespace :open_australia_proxy, defaults: {format: :json} do
        get :representatives
        get 'representatives/:id', to: :representative
      end
    end
  end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
  end

  def results
    search_query = get_params
    @results = Search.new.find_debates(search_query)
  end

  private

  def get_params
    params.permit(:topic)
  end
end

app/views/search/index.html.erb
<%= form_tag '/search/results', method: :get do %>
  <%= label_tag('Search for topics') %>
  <%= text_field_tag('topic') %>
<% end %>

app/views/search/results.html.erb
<%= form_tag post_modal_path, remote:true, class:'search-form' do %>
  <%= fields_for Post.new do |f| %>
    <% @results.each do |result| %>
      <% next if result.nil? %>
      <div class="row success">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <h4><%= result[:who_said_it] %> - <%= result[:what_is_their_party] %>
                <small><%= time_ago_in_words result[:when_they_said_it] %> ago</small>
              </h4>
            </div>
            <small>
              <% result[:what_is_their_position].each do |position| %>
                <%= position %>
                <br/>
              <% end %>
            </small>
          </div>
          <div class="panel-body">
            <div class="col-md-2">
              <%= check_box_tag 'post[targets_ids][]', result[:id], false, class:'targets' %>
              <img class="img-responsive img-thumbnail" src="<%= result[:what_do_they_look_like] %>" alt=""/>
            </div>
            <div class="col-md-10">
              <%= result[:what_they_said].html_safe %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>