config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  resources :posts
  post 'post/modal', to:'posts#modal', as: :post_modal
  post 'post/modal/create', to:'posts#troll', as: :post_troll

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#results'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers:        {omniauth_callbacks: "omniauth_callbacks"}

  get 'guide', to: 'home#guide'
  get 'video', to: 'home#video'
  root 'home#index'

  get 'sign_up/modal', to: 'home#sign_up_modal', as: :sign_up_modal

  namespace :api do
    namespace :v1 do
      namespace :open_australia_proxy, defaults: {format: :json} do
        get :representatives
        get 'representatives/:id', to: :representative
      end
    end
  end


end

app/views/layouts/_flash_message.html.erb
<div class="alert <%= tb_alert_class_for(type) %> fade in">
  <button class="close" data-dismiss="alert">×</button>
  <%= message %>
  <% if defined?(details) %>
    <% unless details.nil? %>
      <a href="JavaScript:void(0);" class="alert-link"><small>More..</small></a>
      <div class="details" style="display:none;">
        <small>
          <%= details %>
        </small>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <% unless type.include? 'details' %>
      <% details = nil
        if flash.key? "#{type}_details"
          details = flash["#{type}_details"]
        end
      %>
      <%= render partial:'layouts/flash_message', locals:{type:type, message:message, details:details} %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>
      <%= pluralize(model.errors.count, "error") %>
      <% if defined?(message) and !message.nil? %>
        <%= message %>
      <% else %>
        prohibited this <%= model.class.model_name.human %> from being saved:
      <% end %>
    </strong>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to GovTroll, root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Guide", guide_path %></li>
        <li><%= link_to "Video", video_path %></li>
      </ul>
      <%= form_tag('/search/results', {method: :get, class:'navbar-form navbar-left', role:'search'}) do %>
        <div class="form-group">
          <input type="text" placeholder="Search" name="topic" class="form-control"/>
          <button type="submit" class="btn btn-success">
            Troll Search
            <i class="fa fa-search"></i>
          </button>
        </div>
      <% end %>

      <ul class="nav navbar-nav">
        <li>
          <div style="margin-top: 4px;">
            <% if user_signed_in? %>
              <a href="JavaScript:void(0);" class="btn btn-success post-open-modal" role="button">
                Troll
                <i class="fa fa-comment"></i>
              </a>
            <% else %>
              <%= link_to sign_up_modal_path, class:'btn btn-success sign-up-modal', role:'button', remote:true do %>
                Troll
                <i class="fa fa-comment"></i>
              <% end %>
            <% end %>
          </div>
        </li>
      </ul>

      <% if user_signed_in? %>
        <div class="btn-group pull-right">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-cog fa-fw"></i>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user fa-fw"></i>
                <%= current_user.name %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="icon-off"></i>
                Sign out
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GovTroll" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body class="gov-troll">
    <%= render partial:'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render partial:'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div id="modal_container"></div>
  </body>
</html>